# Site settings
title: Plantcam
email: yoman821@gmai.com
description: "LOOK AT THIS BAMBOO"
baseurl: ""
url: "clubhouse149plantcam.github.io"
imgurl: "/assets/img"
jsurl: "/assets/js"

# Build settings
markdown: kramdown
permalink: pretty

sass:
  sass_dir: assets/css
  style: :compressed

gems:
  - jekyll-sitemap
